[package]
name = "arle"
version = "1.0.0"
edition = "2024"
repository = "https://github.com/atirut-w/arle"
description = "Adaptive Run-Length Encoder"
license = "MIT"
readme = "README.md"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.40", features = ["derive"] }
